-- ==========================================
-- 멘토의 공간 - Supabase posts 테이블 생성 SQL
-- ==========================================

-- 1. 기존 테이블이 있다면 안전하게 삭제 (옵션)
-- drop table if exists posts;

-- 2. posts 테이블 생성
create table posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  category text not null,
  tags text[] not null default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Row Level Security (RLS) 활성화
alter table posts enable row level security;

-- 4. 보안 정책 (Policies) 설정
-- 초보 개발자의 연동 테스트 편의를 위해 일단 누구나 CRUD가 가능하도록 설정해 두었습니다.
-- 추후 서비스 배포 시에는 쓰기/삭제 권한을 인증된 사용자만 가능하도록 강화하는 것을 추천합니다.

-- 조회 권한: 누구나 가능
create policy "Allow public read access"
  on posts for select
  using (true);

-- 등록 권한: 누구나 가능 (테스트 편의용)
create policy "Allow public insert access"
  on posts for insert
  with check (true);

-- 삭제 권한: 누구나 가능 (테스트 편의용)
create policy "Allow public delete access"
  on posts for delete
  using (true);
