-- ==========================================
-- 멘토의 공간 - Supabase 데이터베이스 스키마 정의 SQL
-- ==========================================

-- 1. 기존 테이블/트리거 정리
-- drop trigger if exists on_auth_user_created on auth.users;
-- drop function if exists public.handle_new_user();
-- drop table if exists posts;
-- drop table if exists users;

-- 2. users 테이블 생성
create table users (
  id uuid references auth.users on delete cascade primary key,
  username text,
  email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. posts 테이블 생성
create table posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  category text not null,
  tags text[] not null default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references users(id) on delete cascade
);

-- 4. Row Level Security (RLS) 활성화
alter table users enable row level security;
alter table posts enable row level security;

-- 5. 보안 정책 (Policies) 설정
-- 사용자 조회 권한: 누구나 가능
create policy "Allow public read access on users"
  on users for select
  using (true);

-- 포스트 조회 권한: 일반 카테고리는 누구나 가능, 멘토의 지혜는 로그인한 멤버십 회원만 가능
create policy "Allow read for everyone on non-membership posts"
  on posts for select
  using (category != '멘토의 지혜');

create policy "Allow read for members on membership posts"
  on posts for select
  using (category = '멘토의 지혜' and auth.role() = 'authenticated');

-- 포스트 등록 권한: 누구나 가능 (인증 정보 유무에 관계없이 데모 및 개발 편의성 보장)
create policy "Allow public insert access on posts"
  on posts for insert
  with check (true);

-- 포스트 삭제 권한: 누구나 가능 (데모용)
create policy "Allow public delete access on posts"
  on posts for delete
  using (true);

-- 포스트 수정 권한: 누구나 가능 (데모용)
create policy "Allow public update access on posts"
  on posts for update
  using (true);

-- 6. auth.users 가입 시 public.users로 자동 연동을 위한 트리거 및 함수 정의
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, username, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.email
  );
  return new;
end;
$$ language plpgsql security definer;

-- 신규 유저 생성 트리거 연결
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

